-- AlterTable
ALTER TABLE "tenant" ADD COLUMN IF NOT EXISTS "password_days" INTEGER NOT NULL DEFAULT 30;

-- AlterTable
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "password_changed_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
